version: '3.7'

networks:
  my-moments:
    driver: bridge
    name: my-moments

services:

  mysql:
    image: mysql:8.0
    networks:
      - my-moments
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my-moments
      - MYSQL_USER=my-moments-user
      - MYSQL_PASSWORD=my-moments-password123
    ports:
      - 3366:3306

  jenkins:
    image: jenkins/jenkins:2.289.3-lts-slim
    networks:
      - my-moments
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins