version: '3'

services:

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my-moments
      - MYSQL_USER=my-moments-user
      - MYSQL_PASSWORD=my-moments-password123
    ports:
      - 3306:3306