version: '3.7'

networks:
  my-moments:
    driver: bridge
    name: my-moments

services:

  postgres:
    restart: always
    image: postgres:13.3-alpine3.14
    networks:
      - my-moments
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: my-moments
      POSTGRES_USER: my-moments-user
      POSTGRES_PASSWORD: my-moments-password
    container_name: postgres

  jenkins:
    image: jenkins/jenkins:2.305-jdk11
    networks:
      - my-moments
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins