spring:
  #
  # JDBC properties
  #
  datasource:
    pool:
      initial-size: 100
      max-idle-time: 30m
      max-size: 500
      validation-query: SELECT 1
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  #
  # JPA
  #
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  #
  # Flyway
  #
  flyway:
    locations: classpath:db/migration/postgres
    schemas: my_moments
    default-schema: my_moments