spring:
  #
  # JDBC properties
  #
  datasource:
    pool:
      initial-size: 100
      max-idle-time: 30m
      max-size: 500
      validation-query: SELECT 1
    url: jdbc:mysql://192.168.99.100:3306/my-moments?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
    username: my-moments-user
    password: my-moments-password123
  #
  # JPA / HIBERNATE
  #
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  #
  # Flyway
  #
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: my_moments_schemas
    validate-on-migrate: true
    table: my_moments_schema_version
    locations: classpath:db/migration
