server:
  port: 8080
spring:
  #
  # JDBC properties
  #
  r2dbc:
    pool:
      initial-size: 100
      max-idle-time: 30m
      max-size: 500
      validation-query: SELECT 1
    url: r2dbc:pool:mysql://myapp-mysql:3306/my-moments?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
    username: my-moments-user
    password: my-moments-password123
  #
  # JPA / HIBERNATE
  #
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
#spring.datasource.schema=classpath:sqlScripts/mysql/schema-mysql.sql
#spring.datasource.data=classpath:sqlScripts/mysql/data-mysql.sql
#
# Custom properties
#
my-moments:
  #
  # Swagger
  #
  swagger:
    authorization-header: Authorization
    contact-email: https://github.com/NowakArtur97
    contact-name: Artur Nowak
    contact-url: https://github.com/NowakArtur97
    description: REST API of the social network
    license: MIT
    license-url: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    path-selectors: /api/**
    terms-of-serviceUrl: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    title: MyMoments
    version: 1.0