spring:
  #
  # JDBC properties
  #
  datasource:
    pool:
      initial-size: 100
      max-idle-time: 30m
      max-size: 500
      validation-query: SELECT 1
    url: jdbc:postgresql://192.168.99.100:5432/my-moments
    username: my-moments-user
    password: my-moments-password
    driverClassName: org.postgresql.Driver