#
# Server
#
server:
  port: 8088
#
# Spring Boot
#
spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:ci}
  #
  # Flyway
  #
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: my_moments_schemas
    validate-on-migrate: true
    table: my_moments_schema_version
  #
  # JPA / HIBERNATE
  #
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#
# Spring Boot Actuator
#
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false
#
# Custom properties
#
my-moments:
  default-user-role: USER_ROLE
  #
  # Swagger
  #
  swagger:
    authorization-header: Authorization
    contact-email: https://github.com/NowakArtur97
    contact-name: Artur Nowak
    contact-url: https://github.com/NowakArtur97
    description: REST API of the social network
    license: MIT
    license-url: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    path-selectors: /api/**
    terms-of-serviceUrl: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    title: MyMoments
    version: 1.0
  #
  # JWT
  #
  jwt:
    secretKey: secret
    validity: 36000000
    authenticated-ant-matchers: /api/v1/**
    ignored-endpoints:
      - /registration
      - /authentication
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources
      - /configuration/security
      - /swagger-ui.html
      - /webjars
    ignored-ant-matchers:
      - /api/v1/registration/**
      - /api/v1/authentication/**
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources/**
      - /configuration/security
      - /swagger-ui.html
      - /webjars/**
    authorization-header: Authorization
    authorization-type: Bearer
    authorization-header-length: 7
