#
# Server
#
server:
  port: 8080
#
# Spring Boot
#
spring:
  profiles:
    active: dev
#
# Custom properties
#
my-moments:
  #
  # Swagger
  #
  open-api:
    authorization-header: Authorization
    contact-email: https://github.com/NowakArtur97
    contact-name: Artur Nowak
    contact-url: https://github.com/NowakArtur97
    description: REST API of the social network
    license: MIT
    license-url: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    path-selectors: /api/**
    terms-of-serviceUrl: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    title: MyMoments
    version: 1.0