#
# Server
#
server:
  port: 8080
#
# Spring Boot
#
spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
#
# Custom properties
#
my-moments:
  default-user-role: ROLE_USER
  #
  # Swagger
  #
  swagger:
    authorization-header: Authorization
    contact-email: https://github.com/NowakArtur97
    contact-name: Artur Nowak
    contact-url: https://github.com/NowakArtur97
    description: REST API of the social network
    license: MIT
    license-url: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    path-selectors: /api/**
    terms-of-serviceUrl: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    title: MyMoments
    version: 1.0
  #
  # JWT
  #
  jwt:
    secretKey: secret
    validity: 36000000
    authenticatedAntMatchers: /api/v1/**
    ignoredEndpoints:
      - /registration
      - /authentication
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources
      - /configuration/security
      - /swagger-ui.html
      - /webjars
    ignoredAntMatchers:
      - /api/v1/registration/**
      - /api/v1/authentication/**
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources/**
      - /configuration/security
      - /swagger-ui.html
      - /webjars/**
    authorizationHeader: Authorization
    authorizationHeaderLength: 7
