CREATE TABLE my_moments.comment (
    "id" SERIAL PRIMARY KEY,
    "user_id" INT NOT NULL,
    "post_id" INT NOT NULL,
    "uuid" VARCHAR(36) NOT NULL,
    "content" TEXT DEFAULT '',
    "create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "modify_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "version" INT DEFAULT 0 NOT NULL,

    CONSTRAINT "FK_USER_COMMENT" FOREIGN KEY ("user_id") REFERENCES my_moments.user ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_POST_COMMENT" FOREIGN KEY ("post_id") REFERENCES my_moments.post ("id") ON DELETE CASCADE ON UPDATE CASCADE
);