server:
  port: 8080
spring:
  #
  # JDBC properties
  #
  r2dbc:
    pool:
      initial-size: 100
      max-idle-time: 30m
      max-size: 500
      validation-query: SELECT 1
    url: r2dbc:pool:mysql://myapp-mysql:3306/my-moments?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
    username: my-moments-user
    password: my-moments-password123
  #
  # JPA / HIBERNATE
  #
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
#spring.datasource.schema=classpath:sqlScripts/mysql/schema-mysql.sql
#spring.datasource.data=classpath:sqlScripts/mysql/data-mysql.sql