CREATE TABLE `post` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `uuid` VARCHAR(36) NOT NULL,
    `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `modify_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `version` INT DEFAULT 0 NOT NULL,
    `caption` VARCHAR(1000) DEFAULT '',
    
    PRIMARY KEY (`id`),
    CONSTRAINT `FK_USER_POST` FOREIGN KEY (`user_id`)
        REFERENCES `user` (`id`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `picture` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `post_id` INT NOT NULL,
    `uuid` VARCHAR(36) NOT NULL,
    `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `modify_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `version` INT DEFAULT 0 NOT NULL,
    `photo` MEDIUMBLOB NOT NULL,
    
    PRIMARY KEY (`id`),
    CONSTRAINT `FK_POST_PICTURE` FOREIGN KEY (`post_id`)
        REFERENCES `post` (`id`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;