CREATE TABLE `comment` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `post_id` INT NOT NULL,
    `uuid` VARCHAR(36) NOT NULL,
    `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `modify_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `version` INT DEFAULT 0 NOT NULL,
    `content` VARCHAR(200) DEFAULT '',
    
    PRIMARY KEY (`id`),
    CONSTRAINT `FK_USER_COMMENT` FOREIGN KEY (`user_id`)
        REFERENCES `user` (`id`)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_POST_COMMENT` FOREIGN KEY (`post_id`)
        REFERENCES `post` (`id`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;