CREATE TABLE `role` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(40) NOT NULL,
    
    PRIMARY KEY(`id`),
    UNIQUE KEY `ROLE_NAME_UNIQUE` (`name`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;