ALTER TABLE `user` MODIFY COLUMN `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `user` MODIFY COLUMN `modify_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `user_profile` MODIFY COLUMN `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `user_profile` MODIFY COLUMN `modify_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `role` MODIFY COLUMN `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `role` MODIFY COLUMN `modify_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE `user_profile` MODIFY COLUMN `gender` VARCHAR(40) NOT NULL;