ALTER TABLE `user` MODIFY COLUMN `version` int DEFAULT 0 NOT NULL;
ALTER TABLE `user_profile` MODIFY COLUMN `version` int DEFAULT 0 NOT NULL;
ALTER TABLE `role` MODIFY COLUMN `version` int DEFAULT 0 NOT NULL;