pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    environment {
        HEROKU_API_KEY = "HEROKU_API_KEY"
        HEROKU_APP_NAME = "HEROKU_APP_NAME"
    }
    stages {
        stage('Give permission to Gradle wrapper') {
            steps {
                sh 'chmod +x gradlew'
            }
        }
        stage('Build') {
            steps {
                echo "HEROKU_APP_NAME = ${env.HEROKU_APP_NAME}"
                echo 'HEROKU_APP_NAME = ${env.HEROKU_APP_NAME}'
                sh './gradlew assemble -Dspring.profiles.active=prod'
                stash includes: '**/build/libs/*.jar', name: 'myMoments'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test -Dspring.profiles.active=ci'
            }
        }
        stage('Promotion') {
            steps {
                timeout(time: 1, unit: 'DAYS') {
                    input 'Deploy to Heroku?'
                }
            }
        }
        stage('Deploy') {
            steps {
                unstash 'myMoments'
                sh 'git push https://heroku:${env.HEROKU_API_KEY}@git.heroku.com/${env.HEROKU_APP_NAME}.git HEAD:refs/heads/master'
            }
        }
    }
}