USE `my-moments`;

CREATE TABLE `user` (
	`user_id` INT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(40) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    
	PRIMARY KEY(`user_id`),
    UNIQUE KEY `USER_USERNAME_UNIQUE` (`username`),
    UNIQUE KEY `USER_EMAIL_UNIQUE` (`email`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;